export enum ProfileContent {
  USER_NAME = 'Mohamed Isthihar',
  FIRST_NAME = 'First Name*',
  LAST_NAME = 'Last Name*',
  EMAIL_ID = 'Email id*',
  DOB = 'Date of Birth',
  MOBILE_NUMBER = 'Mobile Number*',
  GENDER = 'Gender*',
  POSTCODE = 'Post Code',
  CITY = 'City',
  AREA = 'Area',
  UPLOAD_FILE = 'Upload File',
  UPDATE_PROFILE = 'Update Profile',
  STREAM = 'Streams*',
  SUCCESS_MESSAGE = 'Profile Updated Successfully',
  ERROR_MESSAGE = 'Profile not updated, Please try again',
  UPLOADE_IMAGE_MESSAGE = 'Unable to upload profile image at the moment. Please try again later.',
  PROFILE_TITLE = 'Profile Details',
  VERIFY_MOB = 'Verify',
  RESEND_OTP = 'Resend OTP',
  VERIFY_MOB_ERROR = 'OTP Verification failed',
  VERIFY_MOB_SUCCESS = 'OTP Verified successfully',
  OTP_ERROR_MESSAGE = 'Something went wrong, Please try again later',
  MOBILE_VERIFICATION_ERROR = 'Mobile Number is not verified, Verify the Mobile Number',
  IMG_MAX_SIZE = 'MAX SIZE : 2 MB'
}
