version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
      dockerfile: Dockerfile_staging
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: development
