/* eslint-disable prettier/prettier */
export enum CompareInfoConstant{
    ESTD_YEAR='Estd Year',
    OWNER_SHIP= 'Ownership',
    CAMPUS_SIZE= 'Campus Size',
    TOTAL_STD_INTAKE= 'Total Student Intake',
    TOTAL_FACULTY= 'Total Faculty',
    BOYS_HOSTEL='Boys Hostel',
    GIRLS_HOSTEL='Girls Hostel',
    LIBRARY='Library',
    PG_2YRS='PG [2 Year]',
    PG_3YRS='PG [3 Year]',
    PG_4YRS='PG [4 Year]',
    PG_5YRS='PG [5 Year]',
    TTL_STUDENTS=' Total Students',
    BOYS='Boys',
    GIRLS='Girls',
    WITHIN_STATE='Within State',
    OUTSIDESTATE='Outside State',
    OUTSIDECOUNTRY='Outside Country',
    ECO_BACKWARD='Economic Backward',
    SOCIAL_CHALLENGED='Socially Challenged',
    FILLED_SEATS='Filled Seats',
    NO_STD_PLACED='No of Students Placed',
    NO_STD_GRADUATED='No of Students Graduated',
    UG_SALARY=' UG Salary',
    PURSUING='Pursuing',
    GRADUATED='Graduated',
    PATENS_PUBLISHED= 'Patent Published',
    PATENS_GRANTED= 'Patent Granted',
    SPONSORED_RESEARCH= 'Sponsored Research',
    CONSULTANCY_PROJECT= 'Consultancy Project',
    TOTAL= 'Total',
    NEW_EQUIQMENT= 'New Equipment',
    ENG_WORKSHOP= 'Engineering Workshop',
    CREATION_CAPTIAL_ASSETS= 'Creation of Capital Assets',
    SALARIES= 'Salaries',
    MAINTENCE_ACADEMIC= 'Maintenance of Academic Infrastructure',
    SEMINARS_CONFERENCES_WORKSHOP= 'Seminars / Conferences / Workshops',
    TOTAL_FACULTY_COUNT= 'Total Faculty Count',
    PHD_HOLDERS= 'Ph.D Holders',
    FACULTY_STUDENT_RATIO= 'Faculty - Student Ratio',
    OVERALL_FEE= 'Overall Fee',
    CLG_DETAILS= 'College Details',
    CLG_FACILITIES= 'College Facilities',
    SANCTIONED_INTAKE= 'Sanctioned (Approved) Intake ',
    STUDENT_STRENGTH= 'Student Strength',
    UG= 'UG ',
    FUNDS= 'Funds',
    FEE_STRUCTURE= 'Fee Structure',






} 