export enum ChatSidebarTitle {
  COLLEGE_SUGGEST = 'NEET Predictor AI',
  PINNED = 'Pinned Chats',
  CHAT_LIST = 'Chat History',
  CHANGE_THEME = 'Change Theme',
  CLEAR_ALL_CHATS = 'Clear All Chats',
  LOG_OUT = 'Log out',
  NEW_CHAT = 'New Chat',
  MENU = 'Menu',
  UPDATES = 'Updates',
  HELP = 'Help',
  NEW = 'new',
  DELETE = 'Delete',
  RENAME = 'Rename',
  PIN = 'Pin',
  UN_PIN = 'Unpin',
  QUESTIONS_TXT = 'Remaining Questions',
  UPGRADE_PLAN = 'Upgrade Plan',
  DASHBOARD = 'Dashboard',
  MY_ACCOUNT = 'My Account',
  UPGRADE_YOUR_PLAN = 'Upgrade your plan',
  LAST_VISITED_PAGE = 'lastVisitedPage'
}
